# Generated by Django 5.0.3 on 2024-05-07 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('expenses', 'Expenses'), ('financials', 'Financials'), ('crm', 'CRM'), ('product', 'Product'), ('services', 'Services'), ('hr', 'HR'), ('hr', 'HR')], max_length=20)),
                ('payload', models.CharField(max_length=100000)),
                ('clean_payload', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
