# Generated by Django 5.0.3 on 2024-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='source',
            field=models.CharField(blank=True, choices=[('quickbooks', 'Quickbooks'), ('hubspot', 'HubSpot'), ('stripe', 'Stripe'), ('jira', 'Jira'), ('datadog', 'Datadog')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='category',
            field=models.CharField(blank=True, choices=[('revenue', 'Revenue'), ('expenses', 'Expenses'), ('financials', 'Financials'), ('deals', 'Deals'), ('product', 'Product'), ('services', 'Services'), ('hr', 'HR')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='clean_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
