# Generated by Django 5.0.3 on 2024-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_dashboarddata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
