# Generated by Django 5.0.3 on 2024-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_dashboarddata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
