# Generated by Django 5.0.3 on 2024-04-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('QuickBooks', 'QuickBooks'), ('HubSpot', 'HubSpot'), ('Stripe', 'Stripe'), ('Jira', 'Jira'), ('Salesforce', 'Salesforce'), ('Xero', 'Xero'), ('Mailchimp', 'Mailchimp'), ('Zoho', 'Zoho'), ('ActiveCampaign', 'ActiveCampaign'), ('Freshbooks', 'Freshbooks'), ('Sage', 'Sage'), ('Monday.com', 'Monday.com')], default='QuickBooks', help_text='The service this entry relates to.', max_length=250)),
                ('access_token', models.TextField(max_length=500)),
                ('refresh_token', models.TextField(max_length=500)),
                ('realm_id', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='QuickBooksIntegration',
        ),
    ]
