# Generated by Django 5.0.3 on 2024-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_oauthcredentials_delete_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthcredentials',
            name='realm_id',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
