# Generated by Django 5.0.3 on 2024-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcompanies',
            name='size',
            field=models.CharField(choices=[('SME', '1-9'), ('SME', '10-49'), ('Lower Middle Market', '50-99'), ('Upper Middle Market', '100+')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mmcompanies',
            name='size',
            field=models.CharField(choices=[('SME', '1-9'), ('SME', '10-49'), ('Lower Middle Market', '50-99'), ('Upper Middle Market', '100+')], max_length=100),
        ),
    ]
