# Generated by Django 5.0.3 on 2024-04-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_globalcompanies_size_alter_mmcompanies_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcompanies',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
