# Generated by Django 5.0.3 on 2024-04-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_mmcompanies_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcompanies',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
