# Generated by Django 5.0.3 on 2024-04-26 00:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_mmcompanies_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcompanies',
            name='p_and_l_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('cogs', 'COGS'), ('g&a', 'G&A'), ('s&m', 'S&M'), ('d&a', 'D&A'), ('r&d', 'R&D'), ('interest', 'Interest'), ('non_operating_income', 'Non Operating Income'), ('non_operating_expense', 'Non Operating Expense'), ('taxes', 'Taxes')], max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='globalcompanies',
            name='p_and_l_subcategory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('product_income', 'Product Income'), ('service_income', 'Service Income'), ('subscription_income', 'Subscription Income'), ('royalty_income', 'Royalty Income'), ('other_income', 'Other Income'), ('materials', 'COGS - Materials'), ('direct_labor', 'COGS - Direct Labor'), ('manufacturing_supplies', 'COGS - Manufacturing Supplies'), ('production_overhead', 'COGS - Production Overhead'), ('office', 'G&A - Office'), ('g&a_salaries', 'G&A - Salaries'), ('rent_lease', 'G&A - Rent & Lease'), ('utilities', 'G&A - Utilities'), ('misc.', 'G&A - Misc.'), ('r&d_salaries.', 'R&D - Salaries'), ('product_development', 'R&D - Product Development'), ('software_development', 'R&D - Software Development'), ('s&m_salaries', 'S&M - Salaries'), ('s&m_software', 'S&M - Software'), ('s&m_advertising', 'S&M - Advertising'), ('s&m_commisions', 'S&M - Commisions'), ('county_taxes', 'Taxes - County'), ('state_taxes', 'Taxes - State'), ('federal_taxes', 'Taxes - Federal'), ('sale_of_assets', 'Non-Operating - Sale of Asset Gain/Loss'), ('fx_gain_loss', 'Non-Operating - Foreign Exchange Gain/Loss'), ('investment_income', 'Non-Operating - Investment Income Gain/Loss'), ('grant', 'Non-Operating - Grant Income')], max_length=100), blank=True, default=list, size=None),
        ),
    ]
