# Generated by Django 5.0.3 on 2024-04-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_globalcompanies_p_and_l_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcompanies',
            name='sector',
            field=models.CharField(blank=True, choices=[('information_technology', 'Information Technology'), ('consumer_discretionary', 'Consumer Discretionary'), ('communication_services', 'Communication Services'), ('unknown', 'Unknown'), ('financials', 'Financials'), ('healthcare', 'Healthcare'), ('energy', 'Energy'), ('consumer_staples', 'Consumer Staples'), ('materials', 'Materials'), ('industrials', 'Industrials'), ('utilities', 'Utilities'), ('real_estate', 'Real Estate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalcompanies',
            name='size',
            field=models.CharField(blank=True, choices=[('SME', '1-9'), ('SME', '10-49'), ('Lower Middle Market', '50-99'), ('Upper Middle Market', '100+')], max_length=100, null=True),
        ),
    ]
