# Generated by Django 5.0.3 on 2024-04-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_globalcompanies_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcompanies',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
