# Generated by Django 5.0.3 on 2024-05-13 22:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_remove_mmcompanies_users_mmcompanies_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmcompanies',
            old_name='quartile1_price',
            new_name='low_tier_price',
        ),
        migrations.RenameField(
            model_name='mmcompanies',
            old_name='quartile2_price',
            new_name='mid_tier_price',
        ),
        migrations.RenameField(
            model_name='mmcompanies',
            old_name='quartile3_price',
            new_name='upper_tier_price',
        ),
        migrations.RemoveField(
            model_name='mmcompanies',
            name='quartile4_price',
        ),
        migrations.AlterField(
            model_name='globalcompanies',
            name='p_and_l_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('revenue', 'Revenue'), ('cogs', 'COGS'), ('g&a', 'G&A'), ('s&m', 'S&M'), ('d&a', 'D&A'), ('r&d', 'R&D'), ('interest', 'Interest'), ('non_operating_income', 'Non Operating Income'), ('non_operating_expense', 'Non Operating Expense'), ('taxes', 'Taxes')], max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='mmcompanies',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
